- src/api/evmTokenApi.ts
- src/types/web3.ts
Moved some type definitions out of `evmTokenApi` and into `types/web3.ts` where they belong.
> chore: improved typing for evmTokenApi

- src/store/web3Store.ts
- src/types/web3.ts
branched off https://github.com/altverseweb3/site/pull/13, https://github.com/altverseweb3/site/pull/14
This PR involves changes to the `Web3Store` state and the `web3Store` implementation in preparation for prices and balances loading.
**Removed (as they were unused):**
- `getWalletTokens`
- `getAllTokens`
- `getTokenById`
- `getTokenByAddress`
- `findTokenByAddressAnyChain`
**Added:**
- `tokenBalancesByWallet`: used for internal calculations and tracking inside web3Store when updating balances for a wallet
- `tokenPricesUsd`: used for internal calculations and tracking inside web3Store when updating prices for tokens
- `updateTokenBalances`: function to update token balances with data received from Lambda API
- `updateTokenPrices`: function to update token prices with data received from …
> feat: web3store preparation for prices and balances

- src/components/meta/TokensInitializer.tsx
branch off https://github.com/altverseweb3/site/pull/13, https://github.com/altverseweb3/site/pull/14, https://github.com/altverseweb3/site/pull/15, https://github.com/altverseweb3/site/pull/16
This PR simply updates the `TokensInitializer.tsx` component to fetch token prices and balances for the user upon the page loading, as well as changes to any of these values:
- `sourceChain` or `destinationChain`
- `tokenCount` (for when the token metadata gets loaded)
- `activeWallet` (if the user starts out with wallet disconnected, we need to trigger a reload once their wallet is connected to fetch balances)
> feat: tokens initializer update

- src/app/(dapp)/swap/page.tsx
- src/components/ui/SwapInterface.tsx
- src/components/ui/TokenAmountInput.tsx
- src/components/ui/TokenInputGroup.tsx
- src/components/ui/TokenTransfer.tsx
- src/components/ui/TransactionDetails.tsx
- src/utils/walletMethods.ts
- Removed the exchange rate and gas price (gas price may be added back in the future)
- Calculated the protocol and relayer fee in USD and stored in the TransactionDetails
- Displayed both fees to users
- Adds the `price` and `toTokenPrice` to the displayed prices in the swap interface as a quote is received
> feat: added fees from quote, source/destination prices

- src/components/ui/NumberTicker.tsx
- src/components/ui/PersistentAmountDisplay.tsx
- src/components/ui/SwapInterface.tsx
- src/components/ui/TokenAmountInput.tsx
- src/components/ui/TokenTransfer.tsx
- src/store/web3Store.ts
- src/utils/chainMethods.ts
- src/utils/walletMethods.ts
Automatically fetches quote every 5 seconds provided all necessary input values have been set.
Additionally, the functionality to display "loading..." during a quote load is no longer included - we instead just pulse the previous value. This has been done through the introduction of `PersistentAmountDisplay.tsx`, which tracks previous values and ensures consistent formatting.
@machineboyy I recall we had a conversation about formatting of values with regards to decimal places and commas. Please note that in this PR I have not addressed those points as I cannot recall the exact decision we made on that. I will resolve that in another PR once this has been merged and we have reached a conclusion on formatting and displayed values.
> feat: auto quote

- src/store/web3Store.ts
- src/utils/chainMethods.ts
- src/utils/walletMethods.ts
branch off https://github.com/altverseweb3/site/pull/29
Allows for same chain swaps. Removed prior logic to force different chains, and slightly updated logic to calculate send/receive USD values to support when a same chain quote is used, as `toTokenPrice` will not be included in the quote returned from Mayan.
> feat: allow same chain swap

- package-lock.json
- package.json
- src/components/meta/TokensInitializer.tsx
Uses the `react-idle-timer` package to stop Alchemy calls after 2 minutes of idle time. Immediately after user becomes active, refreshing continues as normal.
> feat: added idle timeout for fetching balances at 2 mins

- src/utils/walletMethods.ts
This PR correctly swaps to the receive wallet that gets set in the transaction details dropdown.
> chore: correctly set receive wallet

- src/components/ui/PersistentAmountDisplay.tsx
This PR leverages the observer API to reactively apply the relevant text size tailwind utility class based on the amount of rendered symbols by the number ticker at any given moment. Font sizes were validated on an iPhone SE and on desktop. An error raised by mayan due to an insufficient input amount or an amount too high does not cause it to behave erratically - it gradually transitions through 0 and through the relevant text size classes piece-wise.
---
iPhone SE:
> fix: use observer API to adjust font sizes in swap component

- src/app/(dapp)/swap/page.tsx
- src/components/meta/TokensInitializer.tsx
- src/components/ui/TokenAmountInput.tsx
- src/components/ui/TokenTransfer.tsx
- src/store/web3Store.ts
- src/types/web3.ts
- src/utils/tokenApiMethods.ts
This PR adds functionality to get the source and destination amount in USD. The displayed USD amounts are instantly responsive to both changes in the quote, as well as pricing data received.
Here is the approach I have gone with:
1. The `Token` type has a new property `alwaysLoadPrice`, which when `true`, will always have the price loaded regardless of the balance status.
2. When a user sets a source or destination token, `alwaysLoadPrice` will be set to `true`. This value will also be persisted in the storage context, so if the site is closed/reloaded then they will not have to re-select the `alwaysLoadPrice` value.
3. Upon loading the storage context, only the stored source and destination token will have the `alwaysLoadPrice` value set to `true`.
4. The source and destination amount in …
> chore: source and destination amounts in USD

- src/utils/tokenApiMethods.ts
- src/utils/walletMethods.ts
This PR simply removes redundant price calculation code from the `fetchQuote` hook, as this is now done using the fetched prices elsewhere.
This PR does not include correcting of the fee calculation - that will be done in the next PR.
> chore: cleanup token transfer

- src/components/ui/TokenImage.tsx
This PR prevents custom tokens which loaded from forcing newly selected tokens from the top 100 to keep using the Lucide `HelpCircle` icon and instead allows them to render their icon png, if available, as expected.
> fix: custom tokens do not cause new tokens to use HelpCircle

- src/types/etherFiABIs.ts
This PR adds the ABIs which are required by `ethers` to instantiate the contracts at the relevant ether.fi contract addresses to allow users to interact with them with their relevant EVM web3 wallet.
> feat: ABIs for etherFi

- src/types/web3.ts
- src/utils/swapTracker.ts
This PR adds the base for tracking of swaps. It includes the `SwapTracker` class, as well as the required updates to the `web3.ts` types which are utilised by this class.
The class has these basic properties which are used to track the progress of a swap:
`pollInterval` - how often to poll the mayan endpoint in ms
`maxRetries` - the max number of retries to have before expiring
`retryCount` - how many polls we have done so far
`isPolling` - the current polling status
`timeoutId` - used to track each polling timeout instance
the `SwapStatus` type has been mapped to include all the key properties returned from the Mayan API when querying a particular swap.
> feat: swap tracker class and updated types

- src/components/ui/earning/DepositModal.tsx
This PR is concerned with requiring that an EVM wallet is connected to conduct a cross-environment swap in the earn section modals.
See https://github.com/altverseweb3/site/commit/7bf078acdc9230aed69b4cca3708a60f1062bfd0 for relevant changes.
---
> feat: require EVM wallet connection for cross-env etherfi swaps

- src/components/ui/earning/DepositModal.tsx
- src/utils/walletMethods.ts
This PR adds a new optional parameter `pauseQuoting` to `useTokenTransfer`, enabling components such as the `DepositModal` to conditionally pause quotes when appropriate, such as when a vault supported asset for direct deposit is selected. 
This allows the input amount on the `DepositModal` to remain as a single consolidated value referencing the `swapAmount`, without actually fetching quotes for swaps that are not required for a direct deposit.
> chore: added pauseQuoting option to useTokenTransfer

- src/components/ui/earning/DepositModal.tsx
PR objectives:
- remove fees prediction in deposit modal
- list balances as being there automatically not just visible with the max button (put balances to the left of the max button)
- place the connect EVM | Sui | Solana buttons where the max button would be if the relevant wallet is not connected otherwise
- place the quote (without the fee) under the amount input so it looks a bit neater
- use the correct native asset symbol (ETH instead of ARB, ETH instead of OP, etc.) in the dropdown and in quotes displayed
---
> feature: remove fees, refine balance and connect wallet in earn modal

- src/components/layout/SiteFooter.tsx
- src/config/etherFi.ts
chore to remove discord link on swap and earn page and fix the ether.fi ecosystem labels
> chore: remove discord link and fix ether.fi vaults ecosystem names

- src/utils/walletMethods.ts
This PR adds all 3 referrer addresses to the `executeEvmSwap` function. I cannot remember why they were not initially included, however, to ensure that all swaps are properly referred we should include all 3 in all swap types.
I have tested EVM swaps with this configuration without any issues.
> chore: added all 3 referrer addresses to EVM swap

- src/store/web3Store.ts
- src/types/web3.ts
This PR adds a "selected chain agnostic" function `getWalletByChain` to the `web3Store`, which takes any `Chain` object as a parameter and compares the `walletType` to the currently connected wallets, and if a match is found, returns the wallet.
This will be critical to our initiative to decouple the `useTokenTransfer` hook, as we can no longer rely on the `getWalletBySourceChain` which leverages the currently set `sourceChain` value in the `web3Store`.
> feat: added getWalletByChain agnostic function to web3Store

- src/components/ui/earning/EarnTable.tsx
This PR is concerned with coloring the table header slightly differently. It also makes the buttons at the bottom for pagination of equal height.
> chore: earn table thead color

- src/types/web3.ts
This PR adds a new interface type which will be used to differentiate between the persisted values for various swap integrations.
This will be included as a Record set in the `web3Store` in future PRs, so each swap integration is able to maintain and persist its own set of values for the swap integration.
> feat: added swap integration type

- .husky/pre-commit
- src/store/storeVersion.ts
- src/store/web3Store.ts
This functionality checks if the web store file has been updated (and as a consequence so has the zustand schema) through a `git diff` as part of the `pre-commit` hook, and if it has, the `STORE_VERSION`, which now lives in a separate file, is incremented and added to the commit as well.
`STORE_VERSION` updates are now automated. This has been tested as `STORE_VERSION` has been updated to `3` automatically on this PR's commit.
> feat: store version automation

- src/app/(dapp)/swap/page.tsx
- src/components/meta/TokensInitializer.tsx
- src/components/ui/AssetBox.tsx
- src/components/ui/SelectChainButton.tsx
- src/components/ui/SwapInterface.tsx
- src/components/ui/TokenInputGroup.tsx
- src/components/ui/TokenTransfer.tsx
- src/components/ui/earning/DepositModal.tsx
- src/utils/tokens/tokenApiMethods.ts
This PR integrates the new handling of active swap state into all of our core components, including the swap page.
Most of the changes involve correctly fetching the active swap state properties such as the `sourceChain`, `destinationChain`, `sourceToken`, `destinationToken` and `transactionDetails` from the `web3Store` helper functions (which really we always should have done as opposed to calling the state directly...), and these functions now return only the value of the active swap state as opposed to one singular value for the entire dApp.
> feat: integrated new active swap state into swap page

- src/app/(dapp)/earn/page.tsx
- src/components/ui/earning/DepositModal.tsx
- src/components/ui/earning/EtherFiModal.tsx
- src/config/etherFi.ts
This PR is straight forward but I would not worry too much about changes to EtherFiModal and DepositModal in terms of spacing, positioning etc, as they will likely be changes soon anyway, this is just to align these modals with the rest of the pages - these were just mock changes.
- Text casing consistency across both modals and on earn page table for etherfi
- Consistent font across numbers and text/heading styling
- added green button styled in the same manner as our standard orange buttons  
- Proper lucide icon usage with wallet and external link icons
As a note: the only thing im really happy with is this stack of buttons (altho probably need another lucide icon for open vault)
before: 
after:
before:
after:
> chore: ui enhncements (& temp modal mock test and button redesign)

- src/app/(dapp)/swap/page.tsx
- src/components/ui/earning/DepositModal.tsx
- src/utils/swap/walletMethods.ts
This PR integrates the swap recorder built by @machineboyy into the `useTokenTransfer` hook. 
In addition, I have replaced the previously redundant `options.type` property from denoting whether the transaction is a `"swap" | "bridge"` to now denoting the source of the swap, in alignment with the swap recorder. Along with that I have removed a whole bunch of conditionals for the whole swap/bridge state (which really should have been removed a long time ago as the bridge page was removed _months_ ago...)
> feat: integrated swap recorder into useTokenTransfer hook

- src/store/storeVersion.ts
- src/store/web3Store.ts
- src/types/web3.ts
A patch for native/l2/wrapped tokens not loading:
This was occuring as a consequence of the `SerializedToken` type omitting the `isNativeGas || isNativeWrapped || isL2Token` types.
> fix: SerializedToken should reflect native/l2/wrapped flags

- src/components/ui/earning/DepositModal.tsx
- src/config/etherFi.ts
- src/store/vaultDepositStore.ts
- src/types/etherFiABIs.ts
- src/utils/etherFi/vaultShares.ts
Adds a new util "vaultShares.ts" this uses the lens contract to query the amount of shares/tokens the user will receive in their chosen vault once they enter in an amount. 
It will also work with cross chain swaps - gets quote from mayan (BNB to USDC  for example), this is used as input for vaultTokensReceieved, which uses previewDeposit from Lens Contract to fetch the conversion from USDC (or any vault accepted token) to liquidUSD.
Direct deposits just use the amounts and token pairs, to fetch using the previewDeposit function. 
Please disregard the old styling, used old branch to branch from.
Changes are also made to casing for deposit modal in vaultDepositStore.ts.
This is still buggy, it will not mess anything up with actually depositing however there are some pairs that still need …
> feat: deposit modal token transcation summary

- src/components/ui/CustomSuiConnectButton.tsx
- src/components/ui/WalletConnectButton.tsx
- src/components/ui/WalletFilter.tsx
This PR decouples the wallet connect buttons from the `WalletFilter.tsx` component - not only simplifying the `WalletFilter` component, but also making the wallet connect buttons a simple, reusable component.
The new `WalletConnectButton` can be used like so:
```ts
// 1. basic usage with EVM wallet type
return (
<WalletConnectButton 
walletType={WalletType.REOWN_EVM}
/>
// 2. advanced usage with custom callbacks:
export const ConnectButtonWithCallbacks = () => {
const handleSuccess = () => {
console.log("Wallet connected successfully!");
// do something actually useful here..
};
const handleError = (error: Error) => {
console.error("Connection failed:", error);
// custom error handling
};
return (
<WalletConnectButton 
walletType={WalletType.REOWN_SOL}
onSuccess={handleSuccess} …
```
> refactor: decoupled wallet connect button from wallet filter

- src/app/(dapp)/earn/page.tsx
- src/app/(dapp)/layout.tsx
- src/components/ui/earning/EarnTable.tsx
- src/components/ui/earning/ProtocolFilter.tsx
- src/components/ui/earning/SortDropdown.tsx
The relevant commit for this PR is: https://github.com/altverseweb3/site/commit/421190fe910167abf81b5f7044ce724208e1d37f
This PR is concerned with adjusting the bottom margins and padding to ensure that the table and earn cards scrollarea is not "cut off" at the bottom of the page by the footer of the dApp layout.
Screenshots follow. 
---
> chore: responsive padding/margin layout adjustments for dApp

- src/components/ui/earning/DepositModal.tsx
- src/utils/swap/walletMethods.ts
Added parseDepositError, similar to existing parseSwapError in walletMethods.tsx to handle error messages in deposit modal.
Added input restrictions to numbers only for deposit modal, not allowing scientific notation which caused some parsing issues.
Also fixed the wrapping behaviour of the error messages in the deposit modal.
> feature: regex to parse error messages to deposit modal and fixes to error/number input handling

- src/app/(dapp)/lending/page.tsx
- src/components/ui/lending/BorrowModal.tsx
- src/config/chains.ts
- src/types/web3.ts
This PR adds the chain picker from Earn to show which chain the user wants to load their current/available positions on Aave.
Note this PR is simply for the UI component - it is not yet functional.
This selected chain state with be tied to the web3Store and directly influence the users metamask wallet state when a chain is switched, and reload the aave assets.
> feat: added chain picker for aave frontend

- src/app/(dapp)/lending/page.tsx
- src/components/ui/lending/BorrowComponent.tsx
- src/components/ui/lending/BorrowModal.tsx
- src/store/storeVersion.ts
- src/store/web3Store.ts
- src/types/web3.ts
This PR adds `aaveChain` as a new property to our web3Store. The point of this property is to track which chain a user wants to supply their supply/borrow positions in (currently just EVM networks). This will work similar to our persisted `sourceChain` and `destinationChain` for the persisted swap states.
This will be a persisted property.
> feat: added aave chain to web3Store

- src/components/ui/lending/BorrowOwnedCard.tsx
- src/components/ui/lending/RepayModal.tsx
- src/components/ui/lending/SupplyButtonComponents.tsx
This PR adds the repay modal to the borrow owned card
screenshots of the repay modal when selected from a borrow card
> feat: enable repay modal in the borrow card repay modal

- src/components/ui/lending/AssetDetailsModal.tsx
- src/components/ui/lending/BorrowOwnedCard.tsx
- src/components/ui/lending/BorrowUnownedCard.tsx
- src/components/ui/lending/SupplyComponent.tsx
- src/components/ui/lending/SupplyOwnedCard.tsx
- src/components/ui/lending/SupplyUnownedCard.tsx
- src/types/aaveV3ABIs.ts
- src/utils/aave/fetch.ts
this change enables all details components to show the asset extra details
Token navigation example 
computer
iphone
> feat: enable asset details modal

- src/components/ui/lending/BorrowComponent.tsx
- src/components/ui/lending/SupplyAvailablePositionsHeader.tsx
- src/components/ui/lending/SupplyComponent.tsx
Updated lending to be consistent with supply and borrow headers for accordions
Borrow and Supply for available positions and borrow owned positions now follow consistent styling 
The headers for every single accordion is incorrect in borrow. As such I have made the supply available positions header a reusable component which is now used for the borrow headers.
> chore: fix bad accordion headers

- src/app/(dapp)/lending/page.tsx
- src/components/ui/lending/SupplyCollateralModal.tsx
- src/components/ui/lending/WithdrawModal.tsx
- src/config/aave.ts
- src/utils/aave/fetch.ts
- src/utils/aave/interact.ts
please https://github.com/altverseweb3/site/commit/0607112599fd8c7aef05369add5a5d711b9191d5
This PR is concerned with consolidating everything to do with `aave` configurations into a single object to serve as a single source of truth to avoid repetition or divergences and to promote extendability. Most notably `isChainSupported` function which had the chain numbers hard-coded in the function were moved up from the `fetch` hook into the configuration.
> refactor: single source of truth for aave chain config

- src/components/ui/lending/SupplyUnownedCard.tsx
This PR resolves a bug where the icon name was erroneously used as the description for an asset on `SupplyUnownedCard.tsx`.
> fix: use ticker instead of icon name for description

- src/components/ui/lending/AssetDetailsModal.tsx
- src/components/ui/lending/BorrowUnownedCard.tsx
- src/components/ui/lending/SupplyOwnedCard.tsx
- src/components/ui/lending/SupplyUnownedCard.tsx
- src/types/aave.ts
- src/utils/aave/fetch.ts
LTV calculations were using default values and were not being calculated properly additionally this was also the case for a % of total supplied. These have been addressed in this PR as well as standardising the color of the details button.
> fix: ltv asset details and total supplied calculations

- src/components/ui/lending/RiskDetailsModal.tsx
This fixes the styling of the risk details modal and makes it much more aesthetically pleaseing.
> chore: fix styling on risk details modal

- src/components/ui/SelectTokenButton.tsx
This PR resolves an issue where the `userBalanceUsd` value would briefly flash the non-rounded value. I also removed the `formatAddress` function in favour of the now shared `truncateAddress` from `utils/formatters`.
> fix: resolved issue with balance usd display in SelectTokenButton

- src/components/meta/TokensInitializer.tsx
- src/components/ui/SelectTokenButton.tsx
branch off #236, will rebase
The only file change relevant to this PR is `TokensInitializer.tsx`
This PR resolves the infinite loop on loading balances and prices. The issue was that the recent fix to the balance display #231. Since #231 we update the `sourceToken` and `destinationToken` objects when the token balances/prices are updated. The issue is that these are also dependencies on our `getPricesAndBalances` call in `TokensInitializer.tsx`... meaning each time the function completes it re-triggers itself.
The fix is to instead use the `sourceToken.id` and `destinationToken.id` instead of the entire objects as dependencies - that way the `getPricesAndBalances` will only run when the actual selected values change, not just ANY property on the token (such as the balance or price).
> bugfix: balance prices infinite loop

- src/hooks/useSwapHistory.ts
- src/hooks/useSwapTracking.ts
- src/utils/swap/swapHistory.ts
This PR removes the debugging `console.log` statements, and corrects some usage to `console.error` in all files related to tracking swap history.
This is part of the initiative to cleanup our incredibly noisy debugging console log - doing it section by section.
> refactor: removed debugging console logs from swap history

- src/utils/swap/walletMethods.ts
This PR updates the Solana RPC url used for executing swaps from Solana. I have tested that this works and have not found any issues with rate limiting.
We can also remove the `NEXT_PUBLIC_ALCHEMY_API_KEY` from our Vercel config now.
> chore: updated solana RPC url

- src/store/storeVersion.ts
- src/store/web3Store.ts
This PR parameterises the default `sourceChain` and `destinationChain` values for swap sections. The issue is that the `defaultDestinationChain` is currently Solana - which obviously does not make sense for either Earn or Lending, given that in Earn we only support Ethereum vaults currently, and in Lending we only support EVM positions.
This should resolve the error logs we see when on the Earn or Lending sections regarding Solana balance/price fetching.
> feature: parameterised default chains for swap section creation

- src/app/(dapp)/layout.tsx
- src/components/meta/AaveClientProvider.tsx
- src/config/aave/aaveClient.ts
branch off #273 
This PR integrates the `AaveClientProvider` into the `(dapp)/layout.tsx` such that the client configuration and state can be easily used throughout the dApp.
**Why are we putting it at `(dapp)/layout.tsx`, not `(dapp)/lending/layout.tsx`?**
This was my initial thought too. However, given that we intend to onboard other Aave features down the line (in particular earn vaults), I figured it would be best to future proof and set this client provider at the dApp level rather than a particular page.
Additionally, the client is extremely resource efficient and will not have an impact on performance. When the client is not being actively called (i.e. we are not on the `/lending` page), it will just sit there as a configured object.
> feature: aave client provider integration

- src/app/(dapp)/lending/page.tsx
- src/store/storeVersion.ts
- src/store/web3Store.ts
- src/types/web3.ts
This PR replaces the `aaveChain` web3Store property with `selectedAaveChains`, which is instead a persisted property of type `Chain[]`. When the `ChainPicker` is used, the state is stored and will persist across refreshes.
The default selected is an empty list, meaning all chains will be shown as a default.
> feat: added web3store property for selected aave chains

- src/components/ui/TruncatedText.tsx
- src/components/ui/lending/MarketCard.tsx
branched off from https://github.com/altverseweb3/site/pull/290
please consider only https://github.com/altverseweb3/site/commit/fdfe153e56f5e1e3bd40d8af094bb25033f4efe6
---
The purpose of this PR to create a `TruncatedText` component which will truncate the length of the text displayed if it reaches the maximum and finish it with an ellipsis. A tooltip on hover of the truncated text will display the full text.
This was motivated by the absurdly long symbol names of some PT tokens.
> feat: truncated markets symbols

- src/components/ui/lending/MarketCard.tsx
Please see just https://github.com/altverseweb3/site/commit/b25a37ca93a589327b4be4bba242e8828ccf73d7
This PR is concerned with extracting more information into the incentives list.
The rationale is that we may want to display some of this information as part of the card or some tooltip modal in the future. For example: we might want to show which reward tokens we get a multiplier for, etc.
> feat: extend aave incentive props

- src/config/etherFi.ts
this PR resolves an incorrect address used on the vault deposit assets for sdeusd. It was set to the address of [sUSDe](https://etherscan.io/address/0x9d39a5de30e57443bff2a8307a4256c8797a3497), which is NOT an approved deposit asset for Market Neutral USD.
This resolves the below bug:
now:
> bugfix: resolved incorrect address on sdeusd

- src/components/meta/SingleMarketUserState.tsx
- src/components/ui/lending/AggregatedMarketUserState.tsx
- src/components/ui/lending/DashboardContent.tsx
please see just https://github.com/altverseweb3/site/pull/313/commits/f531f269cbf174dfde5ab3aa996b455d1331dd51
This PR is concerned with calculating e-mode. If all markets' statuses e-mode are enabled, then e-mode is displayed as enabled, if all markets' statuses e-mode are disabled, then e-mode is displayed as disabled, but otherwise it is displayed as mixed.
> feat: lending calculate e mode

- src/utils/lending/transactions.ts
Please see just https://github.com/altverseweb3/site/commit/a632f81455d92de27151f22b9159be8f29c590a1
this PR is concerned with accounting for the underlying reserve as part of the unique transaction key for lending.
It was discovered that `__typename` and `txHash` along with other parameters were not enough to uniquely identify transactions because multiple different collateral txs can be bundled into a single tx as can be seen in the above screenshot.
> fix: lending history txs underlying asset

- src/components/ui/lending/MarketCard.tsx
this PR adds the market icon to market cards (like we have done in the user open supply/borrow position cards).
> chore: added market icon to market card

- src/types/web3.ts
- src/utils/swap/walletMethods.ts
this PR moves the definitions for the token transfer interfaces to `types/web3.ts` and exports them such that they can be used by components which use the `useTokenTransfer` hook, without having to individually define all the props.
> refactor: moved token transfer interfaces to export from types/web3

- src/app/(dapp)/test/page.tsx
- src/components/ui/lending/AggregatedMarketUserState.tsx
- src/components/ui/lending/DashboardContent.tsx
- src/components/ui/lending/RiskDetailsModal.tsx
This PR is concerned with implementing the "risk details" modal - which is only an available modal for and on chains where borrow positions are open for the user.  In order to display relevant data, the health factor and LTV and maximum LTV and liquidation threshold, per-market, where borrow positions are open, need to be available. 
The liquidation threshold is available in the market state data.
The maximum LTV is also available in the market state data.
In order to calculate the *current LTV*, the collateral and debt on the relevant market needs to be leveraged - as such `borrowData` has been extended to record it, per-chain and the calculation is done in `AggregatedMarketUserState.tsx`
---
Desktop:
Tablet:
Mobile:
---
Proof of parity:
> feat: lending risk details

- src/components/ui/lending/MarketCard.tsx
- src/components/ui/lending/MarketContent.tsx
this PR adds the `AssetDetailsModal` to the `MarketCard` components. Since these already use the `UnifiedMarketData` type, no mapping was required.
> feat: added asset details to market-cards

- src/components/ui/lending/SupplyAssetModal.tsx
- src/utils/swap/walletMethods.ts
this PR adds an error message detail to the supply asset modal when an error occurs during quote fetching.
I have also improved the coverage of error catching, particularly when setting `quoteError` as there were some cases that were previously being missed.
I have also changed the font of the supply details to be consistent with other modals (mono and semibold).
> feat: added error message display for lending

- src/components/ui/lending/SupplyAssetModal.tsx
this PR adds the `WalletConnectButton` to the `SupplyAssetModal` to appear conditionally when `ensureCorrectWalletTypeForChain(sourceChain)` returns `false`.
> feat: added wallet connect button logic to supplyassetmodal

- src/app/(dapp)/lending/page.tsx
- src/components/ui/lending/AvailableBorrowContent.tsx
- src/components/ui/lending/AvailableSupplyContent.tsx
- src/components/ui/lending/DashboardContent.tsx
- src/components/ui/lending/UserBorrowContent.tsx
- src/components/ui/lending/UserSupplyCard.tsx
- src/components/ui/lending/UserSupplyContent.tsx
this PR passes through the completed `handleSupply` hook as a prop to all children components which implement the `AssetDetailsModal`.
There was also a bug in which open supply/borrow positions were incorrectly showing the same asset name and details for all the open cards. This has been resolved by getting the `currency.address` as opposed to the `market.address` to retrieve the `unifiedMarket`.
> feat: supply integration all modals

- src/components/ui/lending/AssetDetailsModal.tsx
- src/components/ui/lending/DashboardContent.tsx
- src/components/ui/lending/UserSupplyCard.tsx
- src/components/ui/lending/UserSupplyContent.tsx
- src/components/ui/lending/WithdrawAssetModal.tsx
- src/hooks/aave/useAaveInteractions.ts
- src/hooks/lending/useWithdrawOperations.ts
- src/types/aave.ts
this PR adds max withdrawal handling (like we have done with max repay transactions) as per [the docs](https://aave.com/docs/developers/aave-v3/markets/operations#withdraw-assets-prepare-the-execution-plan)
> chore: added max withdraw handling

- src/components/ui/lending/SupplyAssetModal.tsx
- src/types/web3.ts
- src/utils/swap/walletMethods.ts
this PR removes the `quoteError` entirely from the `useTokenTransfer` hook - I realise now that it isn't really necessary and the errors are already displayed by toast notifications - doubling up on these errors is just confusing.
Additionally, the `quoteError` handling was not done properly and was causing multiple quotes to run, delaying the time until a quote was actually received. with this change, I have noticed that quotes load around 3x faster.
> bugfix: removed quote error

- src/app/(dapp)/lending/page.tsx
- src/components/ui/lending/DashboardContent.tsx
- src/components/ui/lending/ToggleCollateralModal.tsx
- src/components/ui/lending/UserSupplyCard.tsx
- src/components/ui/lending/UserSupplyContent.tsx
- src/hooks/aave/useAaveInteractions.ts
- src/hooks/lending/useCollateralToggleOperations.ts
- src/types/aave.ts
branch off #363, please see 0e97d1e0db0dbddf5066b802d91b5b457e05a1e8
---
this PR adds the `ToggleCollateralModal.tsx`. It is a relatively small and simple modal, showing only the current supply position balance, as well as a placeholder for what WILL be the health factor impact.
I have passed down the hook from `lending/page.tsx`, following the same clean pattern we have used for all interactions.
The only issue is that the toggle state is tied to what is received from the SDK call at the `page.tsx` level, so the toggle won't currently update until a refresh is done. 
> [!NOTE]
> the above point about manual refreshes is something we are planning to take care of for all interactions - currently all interactions require a manual refresh to get the latest state. in general, we should close …
> feat: collateral toggle modal

- src/components/ui/lending/ActionModals/BorrowAssetModal.tsx
- src/components/ui/lending/ActionModals/RepayAssetModal.tsx
- src/components/ui/lending/ActionModals/SupplyAssetModal.tsx
- src/components/ui/lending/ActionModals/ToggleCollateralModal.tsx
- src/components/ui/lending/ActionModals/WithdrawAssetModal.tsx
- src/components/ui/lending/AssetDetails/AssetDetailsModal.tsx
- src/components/ui/lending/UserContent/UserSupplyCard.tsx
This PR is concerned with injecting the current health factor into lending action modals. This is a requirement of the health preview hooks as it is a parameter.
Responsivity of modals unaffected.
---
Market Cards  - Supply:
Market Cards - Borrow:
Dashboard Cards - Supply:
Dashboard Cards - Borrow:
Dashboard Cards - Repay:
Dashboard Cards - Withdraw:
Dashboard Cards - Toggle Collateral:
> feature: inject health factor into lending action modals

- src/app/(dapp)/lending/page.tsx
this PR adds a manual refresh button to the to right of the lending page, which is always visible. on click it calls `refetchMarkets`.
> feat: manual refresh button

- src/components/ui/lending/MarketContent/MarketCard.tsx
this PR normalises the market card size by further restricting displayed characters on the reserve name, as well as the precision on the total amount supplied/borrowed.
changes:
- asset name: infinite -> 25
- total supplied value: 4 sig figs -> 3 sig figs
- total borrowed value: 4 sig figs -> 3 sig figs
> chore: normalised market card size

- src/components/ui/lending/ActionModals/BorrowAssetModal.tsx
- src/components/ui/lending/ActionModals/RepayAssetModal.tsx
- src/components/ui/lending/ActionModals/SupplyAssetModal.tsx
- src/components/ui/lending/ActionModals/WithdrawAssetModal.tsx
This PR addresses the requirement for `Dialog` components to have a `DialogTitle`. there is a rather aggressive crashing error user-side otherwise!
> fix: missing DialogTitle in lending modals

- src/components/ui/lending/AvailableContent/AvailableBorrowCard.tsx
- src/components/ui/lending/AvailableContent/AvailableSupplyCard.tsx
- src/components/ui/lending/UserContent/UserBorrowCard.tsx
- src/components/ui/lending/UserContent/UserSupplyCard.tsx
this PR normalises the dashboard cards (in a similar exercise to what I did in #398) to ensure there aren't any stragglers with extra height.
I have applied the same restrictions as done with the Market cards - I have also removed the ugly Tooltip implementation in the available supply/borrow cards and replaced it with `<TruncatedText />`.
> chore: normalised dashboard cards

- .husky/pre-commit
- src/app/(dapp)/lending/page.tsx
- src/components/ui/lending/DashboardContent/DashboardContent.tsx
- src/store/storeVersion.ts
- src/store/uiStore.ts
This PR persists tab selection between `markets` | `history` | `dashboard` and between dashboard tabs `borrow` | `supply` and `available` | `borrow`.
Unfortunately there's still a flash delay where markets gets loaded first. But on `refreshMarkets()` or page refresh not dropping state with a tiny delay is still presently preferable.
The flash delay will be fixed.
> feat: persist lending tab state
