altverseweb3/site

src/utils/tokenMethods.ts

branched off https://github.com/altverseweb3/site/pull/13
- Removed the random functionality to assign balances and wallet tokens from `tokenMethods.ts`
- Improved the composite key logic to be easier to reference and more consistent for future use

feat: removed random logic from tokenMethods

---

src/utils/tokenApiMethods.ts

branch off https://github.com/altverseweb3/site/pull/13, https://github.com/altverseweb3/site/pull/14, https://github.com/altverseweb3/site/pull/15
This PR adds the `tokenApiMethods.ts` file, which acts as a wrapper to combine and safely process asynchronous calls to fetch balance and price data for the connected wallet.
- Straightforward, just a helper function
- Converts raw token balances (hex or decimal strings) to human-readable format
- Handles bigint calculations for precise balance representation
- Properly formats decimal places based on token's decimals
- Trims trailing zeros and handles edge cases
- Provides fallback value on error
- Retrieves active wallet from store and sets loading state
- Concurrently fetches data for both source and destination chains
- Uses …

feat: token api methods wrapper

---

src/components/ui/SelectTokenButton.tsx

branch off: #13, #14, #15, #16, #17
This PR integrates the balances/prices loading into the SelectTokenButton.tsx modal, and removes the ugly loading spinner that was previously there.
Since prices and balances directly update the Token directory in our `web3Store`, which is referenced by this component, the updates required were minimal:
- Added a `useEffect` hook to reload the token values upon changes to the following values: `chainToShow, tokensLoading, isOpen, tokenCount`
- Removed loading spinner entirely

feat: balances prices integration

---

src/utils/mayanSwapMethods.ts
src/utils/walletMethods.ts

Enabled EVM swaps using `ethers` and implementing the `swapFromEvm` function.
Note we are not using EIP-2612 permits to avoid restricting the number of tokens that we support.
This is purely to get swaps functional, there are still a huge number of limitations which I am well aware of:
- No automatic refresh after the swap occurs
- Can only select from the top 100 token list
- No polling to check for success of swap

feat: swap integration

---

src/components/meta/TokensInitializer.tsx

This PR updates the `TokensInitializer.tsx` component to fetch balances and prices every 10 seconds, in addition to the already defined set of dependencies.

feat: update prices and balances every 10 secs

---

package-lock.json
package.json
src/app/page.tsx
src/components/ui/AlertDialog.tsx

The purpose of this PR is to warn users that the product is in Beta. `AlertDialog` of shadcn has been leveraged to achieve this.
---
Mobile Preview:
Tablet Preview:
Desktop Preview:

chore: beta alert

---

package-lock.json
package.json
src/app/layout.tsx
src/app/page.tsx
src/components/layout/SiteHeader.tsx
src/components/ui/AlertDialog.tsx
src/components/ui/ConnectWalletModal.tsx

Added rich coloring to toasts as per https://sonner.emilkowal.ski/. Please ignore changes to `page.tsx` and `AlertDialog.tsx` - this is branched off of https://github.com/altverseweb3/site/pull/26
---
Preview (see bottom right):

chore: style toasts

---

src/components/ui/TokenSwitch.tsx
src/components/ui/TokenTransfer.tsx

The switch button in the middle of the swap component now works.

feat: integrated token/chain switch button

---

src/components/ui/TokenAmountInput.tsx

This PR adds a display of the users balance, as well as the max button to set the source amount to their full current balance.
**Desktop**
**Mobile**

feat: added max and balance

---

src/utils/tokenApiMethods.ts

This PR only fetches prices for tokens that have a balance.

feat: only fetching prices for tokens with a balance

---

package-lock.json
package.json
src/app/(dapp)/layout.tsx
src/components/ui/Slider.tsx
src/components/ui/Switch.tsx
src/components/ui/TokenTransfer.tsx
src/components/ui/TransactionDetails.tsx
src/config/chains.ts
src/store/web3Store.ts
src/types/web3.ts
src/utils/walletMethods.ts

The purpose of this PR is to enable gas drop functionality
---
Desktop:
Tablet:
Mobile:
---
---
Verify that a swap with a gas drop delivers the gas drop to the destination chain.

feat: gas drop

---

public/tokens/native/data.json
src/components/ui/SelectTokenButton.tsx
src/components/ui/TokenImage.tsx
src/types/web3.ts
src/utils/tokenMethods.ts

The purpose of this PR is to support native tokens for Mayan - that is - the token associated with gas on the associated chain such as (ETH, BNB, OP, ARB, L2 ETH, POL, AVAX)

feat: support native tokens

---

src/components/ui/SelectChainButton.tsx

This PR patches the chain icons disappearing when chains are switched rapidly.

fix: chain icons do not disappear

---

src/components/meta/WalletContext.tsx
src/components/ui/ConnectWalletModal.tsx
src/config/chains.ts
src/utils/tokenApiMethods.ts
src/utils/walletMethods.ts

This PR resolves a number of bugs:
1. Sui balances not using decimals
2. Swapping with source as an EVM chain that is different to your current wallet chain would cause the initial swap attempt to fail

chore: bugfix

---

src/components/layout/SiteFooter.tsx

Adds the telegram link to the correct space instead of the random one we set

chore: fix-telegram-link

---

package-lock.json
src/components/ui/PersistentAmountDisplay.tsx
src/components/ui/TokenAmountInput.tsx
src/store/web3Store.ts

This PR includes the following ui updates:
- when prices not available or token/amount is not selected, show nothing for the $ value
- show IBM plex mono wallet balance
- max button / balance display do not show until connected wallet
- default to "auto" for slippage
- fixes inconsistent idle states for send and receive amount - now showing 0 for receive instead of 0.000

feat: ui batch 4 (quick wins)

---

src/utils/nativeAssetBalancesLocal.ts

This PR allows us to fetch the balances of native EVM tokens and of Sui/Solana. Presently untested. Needs to be integrated into the UI.

feat: native balances local

---

src/components/ui/earning/DepositModal.tsx
src/store/vaultDepositStore.ts
src/types/earn.ts
src/utils/walletMethods.ts

branch off #103, will rebase
This PR memoizes the `switchToChain` function, which is best practice and allows it to be used safely in hooks where required.
The only file change relevant to this PR is `walletMethods.ts`.

refactor: memoize chain switch function

---

src/components/ui/earning/DepositModal.tsx

branch off #103, #104, #105, will rebase
This PR concludes the changes required to fully integrate direct and cross chain deposits with tracking and state management.
Tracks deposit transaction states and cancels incomplete processes when modal closes. This is done through use of the `vaultDepositModal`.
The previous half-baked implementation was getting very messy so I re-wrote it to try and achieve a much more linear and DRY pattern. 
The only file relevant to this PR is `DepositModal.tsx`. However, there have been lots of changes and moving things around, so I recommend testing the branch, and reading the file on its own rather than viewing the diff.

feat: deposit modal full integration

---

src/components/ui/earning/EarnTable.tsx

for your consideration:
old variants of "details" and "view" buttons:
new variants:

chore: minor table button restyling

---

src/types/aaveV3Abis.ts
src/utils/aave/fetch.ts
src/utils/aave/format.ts
src/utils/aave/interact.ts

This PR adds a critical flow for the visibility of lending data in Aave.
The changes in this PR bolster our frontend components and allow for propagation of important lending data to our final components.
1. Add aave ABIs to support lending and some additional modal models.
2. refactor fetch to use the new enhanced abis
3. refactor interact to accommodate for the future use cases

feat: add backend functionality to display lending information aave 

---

src/app/(dapp)/earn/page.tsx
src/components/ui/earning/EarnCards.tsx
src/config/chains.ts

Desktop View:
---
Tablet View:
---
Phone View:

chore: redesign earn wallet connection prompt

---

src/config/mayan.ts
src/utils/swap/walletMethods.ts

This PR adds a `config/mayan.ts` file so that values we use and may change for Mayan integration can be controlled easily from a single location.

refactor: added mayan quote/swap config

---

src/components/ui/ProgressBar.tsx

feat: add progress bar for detail modal

feat: add progress bar for detail modal

---

src/utils/aave/interact.ts

feat: repay modal functionality interaction
- Implements the functional call so users can repay their transactions

feat: repay modal functionality interaction

---

src/utils/aave/calculations.ts
src/utils/aave/extendedDetails.ts

Adds functional calls to get details data for the extended details modal.

feat: add functional calls to get details data

---

src/utils/aave/extendedDetails.ts

chore: fix broken import in prod

---

src/components/ui/TokenAmountInput.tsx
src/components/ui/lending/BorrowModal.tsx
src/components/ui/lending/BorrowOwnedCard.tsx
src/components/ui/lending/SupplyCollateralModal.tsx
src/components/ui/lending/SupplyModal.tsx
src/components/ui/lending/SupplyOwnedCard.tsx
src/components/ui/lending/SupplyUnownedCard.tsx
src/components/ui/lending/WithdrawModal.tsx
src/utils/aave/utils.ts
src/utils/common.ts
src/utils/swap/walletMethods.ts

This PR consolidates reimplemented functions such as `formatNumber` or `getHealthFactorColor` into a single place.

feat: consolidate common functionality

---

src/components/ui/lending/BorrowModal.tsx

This PR removes the unnecessary `Chain` object creation in `BorrowModal`.

chore: removed chain object creation

---

src/components/ui/lending/RiskDetailsModal.tsx
src/utils/aave/utils.ts

feat: add risk details modal component for integration on button press in the metrics header.

feat: add risk details modal

---

src/components/ui/lending/SupplyComponent.tsx

this PR adds chain listener functionality on the `aaveChain` persisted web3Store property, parallel to what is currently implemented in `BorrowComponent`.
This involves:
- _nothing new, already done in `BorrowComponent`_
- stable loading of `chainTokens` through `useMemo`
- removal of `window.ethereum` listener, instead using a `useEffect` hook to listen for `aaveChain` changes
- addition of extra safety checks in `loadUserPositions` to avoid loading when tokens are not loaded
- _(new)_
- patch of an erroneous key in `SupplyUnownedCard`

feat: added chain listener functionality for SupplyComponent

---

src/components/ui/lending/AssetDetailsModal.tsx
src/components/ui/lending/BorrowUnownedCard.tsx
src/components/ui/lending/SupplyOwnedCard.tsx
src/components/ui/lending/SupplyUnownedCard.tsx
src/utils/aave/fetch.ts

fix: missing supply and borrow data

---

src/components/ui/lending/SupplyModal.tsx
src/components/ui/lending/SupplyUnownedCard.tsx

This PR refactors the `SupplyModal.tsx` to no longer create a `Token` object. Additionally, I have removed all of the parameters which can instead be referenced directly from the `Token` object that is now passed as a prop to `SupplyModal`.

refactor: removed creation of Token object in favour of props

---

src/config/aave/markets.ts

this PR resolves some incorrect market addresses:
- Ethereum Horizon RWA Market
- Sonic V3 Market
- Ethereum V3 EtherFi Market

bugfix: incorrect market addresses

---

package-lock.json
src/components/ui/lending/DashboardContent.tsx
src/components/ui/lending/UserBorrowCard.tsx
src/components/ui/lending/UserBorrowContent.tsx
src/types/aave.ts

branch off #321, please see 7aa35988d5931c6715ecf235e5b7cdfbc868e9d5
---
this PR adds user borrow open cards following an identical pattern to our implementation of user supply open position cards.
presently we only show the borrowed amount and the APY - @machineboyy please help me with coming up with any additional fields you think we should show here.

feature: user borrow open card

---

src/components/ui/lending/SupplyAssetModal.tsx

branch off #345, please see 7133bd4712a411407a3487bb0f3a1ca192e02fdf
---
this PR adds a simple "please select a source token" message when a user selects a different chain on the `SupplyAssetModal` but does not select a token.
Example:

chore: select source token message

---

src/components/ui/lending/EmodeModal.tsx
src/hooks/aave/useAaveInteractions.ts
src/hooks/lending/useEmodeOperations.ts
src/types/aave.ts

This PR is concerned with refactoring e-mode to use established patterns for hook and type usage.

refactor: e-mode uses established patterns

---

src/app/(dapp)/lending/page.tsx

```
Goodbye mate, you’ve served us well,
Our favourite <Button /> with a tale to tell.
With your hello's you lit the way,
Kept the bugs at bay each day.
Now it’s time to pack you down,
Before we push this code to town.
But don’t be sad, it’s not the end—
Until we meet again, old friend.
```

chore: goodbye mate

---

src/config/tabs.ts

this PR enables the `/lending` tab from the `MainNav`.

feat: enabled lending tab
